var programCode2 = function(processingInstance2) {
with (processingInstance2) {
globall.myImagees = function() {
//var color = function(a, b, c, d) {
//    return [a,b,c,d];
//};
// {
var bl = color(0, 0, 0);
var wh = color(255, 255, 255);
var rd = color(255, 0, 0);
var bu = color(0, 0, 255);
var wn = color(254, 255, 255);
var g = {
    a: color(175,175,175),
    b: color(200,200,200),
    c: color(220,220,220),
    d: color(235,235,235),
    e: color(245,245,245),
    f: color(250,255,255),
};
var tbl = color(0,127);
var twh = color(255,127);
window.myImages=[];
myImages[0]=[];
myImages[0][69]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x',bl, bl, bl, 'x','x','x','x','x','x'],
    ['x','x','x','x',bl, wh, wh, wh, bl, 'x','x','x','x','x'],
    ['x','x','x','x',bl, bl, wh, bl, bl, 'x','x','x','x','x'],
    ['x','x','x','x',bl, wh, wh, wh, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x',bl, bl, bl, 'x','x','x','x','x','x'],
    ['x',bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, 'x','x'],
    ['x','x','x','x','x','x',bl, 'x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, 'x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, 'x','x','x','x','x','x','x'],
];
myImages[0][0]=[];
myImages[0][1]=[];
myImages[0][2]=[];
myImages[0][3]=[];
myImages[0][4]=[];
myImages[0][5]=[];
myImages[0][6]=[];
myImages[0][7]=[];
myImages[0][8]=[];
myImages[0][0][0]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, bl, bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, wh, wh, wh, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, bl, wh, bl, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, wh, wh, wh, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, bl, bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, bl, bl, bl, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x',bl, 'x','x',bl, 'x','x',bl, 'x','x','x','x'],
    ['x','x','x','x','x','x','x','x',bl, 'x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, 'x',bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, 'x','x','x',bl, 'x','x','x','x','x'],
    ['x','x','x','x','x',bl, 'x','x','x','x','x',bl, 'x','x','x','x'],
    ['x','x','x','x',bl, 'x','x','x','x','x','x',bl, 'x','x','x','x'],
];
myImages[0][0][1]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, bl, bl, 'x','x','x','x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x',bl, bl, wh, bl, bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, bl, bl, 'x','x','x','x','x','x','x'],
    ['x','x','x','x','x',bl, bl, bl, bl, bl, 'x','x','x','x','x','x'],
    ['x','x','x','x',bl, 'x','x',bl, 'x','x',bl, 'x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, 'x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, bl, 'x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, 'x','x',bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x',bl, 'x','x','x','x',bl, 'x','x','x','x','x'],
    ['x','x','x','x',bl, 'x','x','x','x','x','x',bl, 'x','x','x','x'],
];
myImages[0][0][2]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, bl, bl, 'x','x','x','x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x',bl, bl, wh, bl, bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, bl, bl, 'x','x','x','x','x','x','x'],
    ['x','x','x','x','x',bl, bl, bl, bl, bl, 'x','x','x','x','x','x'],
    ['x','x','x','x',bl, 'x','x',bl, 'x','x',bl, 'x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, 'x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, 'x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, bl, bl, 'x','x','x','x','x','x','x'],
    ['x','x','x','x','x',bl, 'x','x','x',bl, 'x','x','x','x','x','x'],
    ['x','x','x','x',bl, 'x','x','x','x','x',bl, 'x','x','x','x','x'],
    ['x','x','x','x',bl, 'x','x','x','x','x','x',bl, 'x','x','x','x'],
];
myImages[0][0][3]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, bl, bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, wh, wh, wh, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, bl, wh, bl, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, wh, wh, wh, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, bl, bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, bl, bl, bl, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x',bl, 'x','x',bl, 'x','x',bl, 'x','x','x','x'],
    ['x','x','x','x','x','x','x','x',bl, 'x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x',bl, 'x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, 'x',bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, 'x','x','x',bl, 'x','x','x','x','x'],
    ['x','x','x','x','x',bl, 'x','x','x','x','x',bl, 'x','x','x','x'],
    ['x','x','x','x',bl, 'x','x','x','x','x','x',bl, 'x','x','x','x'],
];
myImages[0][1][0]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, bl, bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, wh, wh, wh, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, bl, wh, bl, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, wh, wh, wh, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, bl, bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, bl, bl, 'x','x','x',bl, 'x','x','x'],
    ['x','x','x','x','x',bl, 'x','x',bl, bl, bl, bl, 'x','x','x','x'],
    ['x','x','x','x','x','x','x','x',bl, 'x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x',bl, bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, 'x','x',bl, 'x','x','x','x','x'],
    ['x','x','x','x',bl, 'x',bl, 'x','x','x','x',bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, 'x','x','x','x','x',bl, 'x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x',bl, 'x','x','x','x','x'],
];
myImages[0][1][1]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, bl, bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, wh, wh, wh, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, bl, wh, bl, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, wh, wh, wh, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, bl, bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x',bl, 'x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, bl, bl, bl, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x',bl, 'x','x',bl, 'x','x',bl, 'x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, 'x',bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, 'x',bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, 'x','x','x',bl, 'x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, 'x','x','x',bl, 'x','x','x','x','x'],
];
myImages[0][1][2]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, bl, bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, wh, wh, wh, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, bl, wh, bl, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, wh, wh, wh, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, bl, bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x',bl, bl, bl, bl, 'x','x',bl, 'x','x','x','x'],
    ['x','x','x','x',bl, 'x','x','x',bl, bl, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x',bl, 'x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x',bl, 'x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, 'x',bl, 'x','x','x','x','x','x'],
    ['x','x','x','x',bl, 'x','x',bl, 'x','x',bl, 'x','x','x','x','x'],
    ['x','x','x','x','x',bl, bl, 'x','x','x','x',bl, 'x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x',bl, 'x','x','x','x','x'],
];
myImages[0][1][3]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, bl, bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, wh, wh, wh, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, bl, wh, bl, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, wh, wh, wh, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, bl, bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x',bl, 'x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, bl, bl, bl, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x',bl, 'x','x',bl, 'x','x',bl, 'x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, 'x',bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, 'x',bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, 'x','x','x',bl, 'x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, 'x','x','x',bl, 'x','x','x','x','x'],
];
myImages[0][2][0]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, bl, bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, wh, wh, wh, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, bl, wh, bl, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, wh, wh, wh, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, bl, bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, bl, bl, bl, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x',bl, 'x','x',bl, 'x','x',bl, 'x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, 'x',bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, 'x','x','x',bl, 'x','x','x','x','x'],
];
myImages[0][3][0]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, bl, bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, wh, wh, wh, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, bl, wh, bl, bl, 'x',bl, 'x','x','x'],
    ['x','x','x','x','x','x',bl, wh, wh, wh, bl, 'x',bl, 'x','x','x'],
    ['x','x','x','x','x',bl, bl, bl, bl, bl, 'x',bl, 'x','x','x','x'],
    ['x','x','x','x',bl, 'x','x','x',bl, 'x',bl, 'x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x',bl, bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x',bl, 'x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x',bl, 'x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x',bl, bl, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x',bl, 'x','x',bl, 'x','x','x','x'],
    ['x','x','x','x',bl, 'x','x',bl, 'x','x','x','x',bl, 'x','x','x'],
    ['x','x','x','x','x',bl, bl, 'x','x','x','x','x',bl, 'x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
];
myImages[0][3][1]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, bl, bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, wh, wh, wh, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, bl, wh, bl, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, wh, wh, wh, bl, 'x',bl, 'x','x','x'],
    ['x','x','x','x','x','x','x',bl, bl, bl, 'x','x',bl, 'x','x','x'],
    ['x','x','x','x','x','x','x','x',bl, 'x','x',bl, 'x','x','x','x'],
    ['x','x','x','x','x','x',bl, bl, bl, bl, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x',bl, 'x','x',bl, 'x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x',bl, 'x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x',bl, bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, 'x','x',bl, 'x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, 'x','x','x',bl, 'x','x','x','x'],
    ['x','x','x','x','x','x',bl, 'x','x','x','x',bl, 'x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
];
myImages[0][4][0]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, bl, bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, wh, wh, wh, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, bl, wh, bl, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, wh, wh, wh, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, bl, bl, 'x','x',bl, 'x','x','x'],
    ['x','x','x','x','x',bl, bl, bl, bl, bl, 'x','x',bl, 'x','x','x'],
    ['x','x','x','x','x',bl, 'x','x',bl, 'x',bl, bl, 'x','x','x','x'],
    ['x','x','x','x','x','x','x','x',bl, 'x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, 'x',bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, 'x','x','x',bl, 'x','x','x','x','x'],
    ['x','x','x','x',bl, bl, 'x','x','x','x','x',bl, 'x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x',bl, 'x','x','x','x','x'],
];
myImages[0][4][1]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, bl, bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, wh, wh, wh, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, bl, wh, bl, bl, 'x',bl, 'x','x','x'],
    ['x','x','x','x','x','x',bl, wh, wh, wh, bl, 'x',bl, 'x','x','x'],
    ['x','x','x','x','x','x','x',bl, bl, bl, 'x',bl, 'x','x','x','x'],
    ['x','x','x','x','x','x',bl, bl, bl, bl, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x',bl, 'x','x',bl, 'x','x','x','x','x','x','x'],
    ['x','x','x','x','x',bl, 'x','x',bl, 'x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, 'x',bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, 'x','x',bl, 'x','x','x','x','x'],
    ['x','x','x','x','x',bl, bl, 'x','x','x',bl, 'x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x',bl, 'x','x','x','x','x','x'],
];
myImages[0][5][0]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x',bl, wh, bl, bl, bl, wh, bl, 'x','x','x','x'],
    ['x','x','x','x','x',wh, wh, wh, wh, wh, wh, wh, 'x','x','x','x'],
    ['x','x','x','x','x','x',bl, wh, wh, wh, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, bl, bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, bl, bl, bl, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x',bl, 'x','x',bl, 'x','x',bl, 'x','x','x','x'],
    ['x','x','x','x','x','x','x','x',bl, 'x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, 'x',bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, 'x','x','x',bl, 'x','x','x','x','x'],
    ['x','x','x','x','x',bl, 'x','x','x','x','x',bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, 'x','x','x','x','x',bl, 'x','x','x','x'],
];
myImages[0][6][0]=myImages[0][2][0];
myImages[0][6][1]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x',bl, 'x',bl, bl, bl, 'x',bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, bl, wh, wh, wh, bl, bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, bl, bl, wh, bl, bl, bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, bl, wh, wh, wh, bl, bl, 'x','x','x','x'],
    ['x','x','x','x','x','x',bl, bl, bl, bl, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, bl, bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x',bl, 'x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x',bl, 'x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, 'x',bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, 'x','x','x',bl, 'x','x','x','x','x'],
    ['x','x','x','x','x',bl, 'x','x','x','x','x',bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, 'x','x','x','x','x',bl, 'x','x','x','x'],
];
myImages[0][7][0]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, bl, bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, wh, wh, wh, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, bl, wh, bl, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, wh, wh, wh, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, bl, bl, 'x','x','x','x','x','x'],
    ['x','x','x',rd, 'x','x','x',bl, bl, bl, 'x','x','x','x','x','x'],
    ['x','x','x','x',rd, bl, bl, 'x',bl, 'x',bl, 'x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x',bl, 'x','x',bl, 'x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, 'x',bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, 'x','x','x',bl, 'x','x','x','x','x'],
    ['x','x','x','x','x',bl, 'x','x','x','x','x',bl, 'x','x','x','x'],
    ['x','x','x','x',bl, 'x','x','x','x','x','x',bl, 'x','x','x','x'],
];
myImages[0][7][1]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, bl, bl, 'x','x','x','x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, wh, 'x','x','x','x','x','x'],
    ['x','x','x','x','x',bl, wh, bl, wh, bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, wh, 'x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, bl, bl, 'x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, bl, bl, bl, 'x','x','x','x','x'],
    ['x','x','x',rd, 'x','x',bl, 'x',bl, 'x','x',bl, 'x','x','x','x'],
    ['x','x','x','x',rd, rd, 'x','x',bl, 'x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x',bl, bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, 'x','x',bl, 'x','x','x','x','x'],
    ['x','x','x','x','x',bl, bl, 'x','x','x','x',bl, 'x','x','x','x'],
    ['x','x','x','x',bl, 'x','x','x','x','x','x',bl, 'x','x','x','x'],
];
myImages[0][7][2]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, bl, bl, 'x','x','x','x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, wh, 'x','x','x','x','x','x'],
    ['x','x','x','x','x',bl, wh, bl, wh, bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, wh, 'x','x','x','x','x','x'],
    ['x','x',rd, 'x','x','x',bl, bl, bl, 'x','x','x','x','x','x','x'],
    ['x','x',rd, 'x','x','x','x',bl, bl, bl, bl, 'x','x','x','x','x'],
    ['x','x','x',rd, 'x','x',rd, 'x',bl, 'x','x',bl, 'x','x','x','x'],
    ['x','x','x','x',rd, rd, 'x','x',bl, 'x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x',bl, bl, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, 'x','x','x',bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, bl, 'x','x','x','x',bl, 'x','x','x','x'],
    ['x','x','x','x',bl, 'x','x','x','x','x','x','x','x','x','x','x'],
];
myImages[0][7][3]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x',bl, bl, bl, 'x','x','x','x'],
    ['x','x','x','x','x','x','x','x',bl, wh, wh, wh, bl, 'x','x','x'],
    ['x','x','x','x','x','x','x','x',bl, wh, wh, bl, bl, 'x','x','x'],
    ['x','x','x','x','x','x','x','x',bl, wh, wh, wh, bl, 'x','x','x'],
    ['x','x','x','x','x','x','x','x',rd, bl, bl, bl, 'x',rd, 'x','x'],
    ['x','x','x','x','x','x',bl, bl, bl, bl, bl, rd, rd, rd, rd, rd ],
    ['x','x','x','x','x',bl, 'x','x','x',bl, rd, 'x','x','x',rd, 'x'],
    ['x','x','x','x','x','x','x','x',bl, 'x','x','x',rd, 'x','x','x'],
    ['x','x','x','x','x','x','x',bl, bl, 'x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, 'x','x',bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x',bl, 'x','x','x','x',bl, 'x','x','x','x','x'],
    ['x','x','x','x',bl, 'x','x','x','x','x','x',bl, 'x','x','x','x'],
    ['x','x','x',bl, 'x','x','x','x','x','x',bl, 'x','x','x','x','x'],
];
myImages[0][8][0]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl,bl,bl,'x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl,wh,wh,wh,bl,'x','x','x','x','x'],
    ['x','x','x','x','x','x',bl,bl,wh,bl,bl,'x','x','x','x','x'],
    ['x','x','x','x','x','x',bl,wh,wh,wh,bl,'x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl,bl,bl,'x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl,bl,bl,bl,'x','x','x','x','x','x'],
    ['x','x','x','x','x',bl,'x','x',bl,'x',bl,bl,'x','x','x','x'],
    ['x','x','x','x','x','x','x',bl,'x',bl,'x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl,'x','x','x',bl,'x','x','x','x','x'],
];
myImages[0][8][1]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl,bl,bl,'x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl,wh,wh,wh,bl,'x','x','x','x','x'],
    ['x','x','x','x','x','x',bl,bl,wh,bl,bl,'x','x','x','x','x'],
    ['x','x','x','x','x','x',bl,wh,wh,wh,bl,'x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl,bl,bl,'x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl,bl,bl,bl,bl,'x','x','x','x','x'],
    ['x','x','x','x','x',bl,'x','x',bl,'x','x',bl,bl,bl,'x','x'],
    ['x','x','x','x','x','x','x',bl,'x',bl,'x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl,'x','x','x',bl,'x','x','x','x','x'],
];
myImages[1]=[];
myImages[1][69]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x',bl, bl, bl, bl, bl, bl, bl, 'x','x','x'],
    ['x','x','x',bl, bl, wh, wh, wh, wh, wh, bl, bl, 'x','x'],
    ['x','x','x',bl, wh, bl, bl, bl, bl, bl, wh, bl, 'x','x'],
    ['x','x',bl, wh, bl, bl, wh, bl, wh, bl, wh, bl, 'x','x'],
    ['x','x',bl, wh, bl, bl, wh, bl, wh, bl, wh, bl, 'x','x'],
    ['x','x',bl, wh, bl, bl, bl, bl, bl, bl, wh, bl, 'x','x'],
    ['x','x',bl, wh, bl, bl, bl, bl, bl, bl, wh, bl, 'x','x'],
    ['x','x',bl, wh, bl, bl, bl, bl, bl, bl, wh, bl, 'x','x'],
    ['x','x',bl, wh, wh, wh, wh, wh, wh, wh, bl, 'x','x','x'],
];
myImages[1][0]=[];
myImages[1][1]=[];
myImages[1][2]=[];
myImages[1][3]=[];
myImages[1][4]=[];
myImages[1][5]=[];
myImages[1][6]=[];
myImages[1][7]=[];
myImages[1][8]=[];
myImages[1][0][0]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x',bl, bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, wh, wh, wh, wh, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, bl, wh, bl, wh, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, bl, wh, bl, wh, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, bl, bl, bl, bl, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, bl, bl, bl, bl, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, wh, wh, wh, wh, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
];
myImages[1][0][1]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x',bl, bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, wh, wh, wh, wh, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, bl, wh, bl, wh, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, bl, wh, bl, wh, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, bl, bl, bl, bl, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, bl, bl, bl, bl, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, bl, bl, bl, bl, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, wh, wh, wh, wh, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
];
myImages[1][0][2]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x',bl, bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, wh, wh, wh, wh, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, bl, bl, bl, bl, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, bl, wh, bl, wh, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, bl, wh, bl, wh, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, bl, bl, bl, bl, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, bl, bl, bl, bl, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, wh, wh, wh, wh, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
];
myImages[1][0][3]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x',bl, bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, wh, wh, wh, wh, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, bl, bl, bl, bl, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, bl, wh, bl, wh, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, bl, wh, bl, wh, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, bl, bl, bl, bl, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, wh, wh, wh, wh, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
];
myImages[1][1][0]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x',bl, bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, wh, wh, wh, wh, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, bl, bl, bl, bl, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, bl, wh, bl, wh, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, bl, wh, bl, wh, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, bl, bl, bl, bl, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, bl, bl, bl, bl, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, wh, wh, wh, wh, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
];
myImages[1][1][1]=myImages[1][0][2];
myImages[1][1][2]=myImages[1][1][0];
myImages[1][1][3]=myImages[1][0][2];
myImages[1][2][0]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x',bl, bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, wh, wh, wh, wh, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, bl, wh, bl, wh, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, bl, wh, bl, wh, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, bl, bl, bl, bl, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, wh, wh, wh, wh, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
];
myImages[1][3][0]=myImages[1][0][1];
myImages[1][3][1]=myImages[1][2][0];
myImages[1][4][0]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x',bl, 'x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, wh, bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, wh, bl, wh, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, bl, bl, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, bl, bl, wh, bl, bl, wh ,bl, 'x','x','x'],
    ['x','x','x',bl, wh, bl, bl, bl, bl, wh, bl, bl, wh, bl, 'x','x'],
    ['x','x','x','x',bl, wh, bl, bl, bl, bl, wh, wh, bl, 'x','x','x'],
    ['x','x','x','x','x',bl, wh, bl, bl, bl, wh, bl, 'x','x','x','x'],
    ['x','x','x','x','x','x',bl, wh, bl, wh, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, wh, bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x',bl, 'x','x','x','x','x','x','x'],
];
myImages[1][4][1]=myImages[1][4][0];
myImages[1][5][0]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x',bl, bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, wh, wh, wh, wh, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, wh, bl, bl, bl, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, bl, wh, bl, wh, bl, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, wh, bl, bl, bl, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, bl, bl, bl, bl, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, wh, wh, wh, wh, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
];
myImages[1][6][0]=myImages[1][0][1];
myImages[1][6][1]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x',bl, bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, wh, wh, wh, wh, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, bl, wh, bl, wh, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, bl, wh, bl, wh, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, bl, bl, bl, bl, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, bl, bl, bl, bl, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, bl, bl, bl, bl, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, bl, bl, bl, bl, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, bl, bl, bl, bl, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, wh, wh, wh, wh, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
];
myImages[1][7][0]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x',bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, 'x','x'],
    ['x','x','x','x',bl, wh, wh, wh, wh, wh, wh, bl, rd, bl, 'x','x'],
    ['x','x','x','x',bl, wh, wh, bl, bl, bl, wh, bl, rd, bl, 'x','x'],
    ['x','x','x','x',bl, wh, bl, wh, bl, wh, bl, bl, rd, bl, 'x','x'],
    ['x','x','x','x',bl, wh, bl, bl, bl, bl, wh, bl, rd, bl, 'x','x'],
    ['x','x','x','x',bl, wh, bl, bl, bl, bl, wh, bl, rd, bl, 'x','x'],
    ['x','x','x','x',bl, wh, wh, wh, wh, wh, wh, bl, bl, bl, 'x','x'],
    ['x','x','x','x',bl, bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
];
myImages[1][7][1]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x',bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl],
    ['x','x','x','x',bl, wh, wh, wh, wh, wh, wh, bl, rd, rd, rd, bl],
    ['x','x','x','x',bl, wh, wh, bl, bl, bl, wh, bl, bl, bl, rd, bl],
    ['x','x','x','x',bl, wh, bl, wh, bl, wh, bl, bl, bl, bl, rd, bl],
    ['x','x','x','x',bl, wh, bl, bl, bl, bl, wh, bl, bl, bl, rd, bl],
    ['x','x','x','x',bl, wh, bl, bl, bl, bl, wh, bl, rd, rd, rd, bl],
    ['x','x','x','x',bl, wh, wh, wh, wh, wh, wh, bl, bl, bl, bl, bl],
    ['x','x','x','x',bl, bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
];
myImages[1][7][2]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x',bl, 'x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x',bl, rd, bl, 'x','x','x','x','x','x','x','x','x'],
    ['x','x','x',bl, rd, bl, rd, bl, 'x','x','x','x','x','x','x','x'],
    ['x','x',bl, rd, bl, bl, bl, rd, bl, 'x','x','x','x','x','x','x'],
    ['x',bl, rd, bl, bl, bl, rd, bl, 'x','x','x','x','x','x','x','x'],
    [bl, rd, bl, bl, bl, rd, bl, rd, bl, 'x','x','x','x','x','x','x'],
    ['x',bl, rd, bl, rd, bl, bl, bl, rd, bl, 'x','x','x','x','x','x'],
    ['x','x',bl, rd, bl, rd, bl, bl, bl, bl, bl, bl, bl, bl, 'x','x'],
    ['x','x','x',bl, 'x',bl, bl, wh, wh, wh, wh, wh, wh, bl, 'x','x'],
    ['x','x','x','x','x','x',bl, wh, wh, bl, bl, bl, wh, bl, 'x','x'],
    ['x','x','x','x','x','x',bl, wh, bl, wh, bl, wh, bl, bl, 'x','x'],
    ['x','x','x','x','x','x',bl, wh, bl, bl, bl, bl, wh, bl, 'x','x'],
    ['x','x','x','x','x','x',bl, wh, bl, bl, bl, bl, wh, bl, 'x','x'],
    ['x','x','x','x','x','x',bl, wh, wh, wh, wh, wh, wh, bl, 'x','x'],
    ['x','x','x','x','x','x',bl, bl, bl, bl, bl, bl, bl, bl, 'x','x'],
];
myImages[1][7][3]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, bl, 'x','x','x',bl, 'x','x','x','x'],
    ['x','x','x','x','x','x','x','x',bl, bl, 'x','x',bl, 'x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x',bl, 'x','x',bl, 'x','x'],
    ['x','x','x','x','x','x','x',bl, bl, 'x','x',bl, 'x','x',bl, 'x'],
    ['x','x','x','x','x','x','x','x','x',bl, 'x','x',bl, 'x',bl, 'x'],
    ['x','x','x','x','x','x','x','x','x','x',bl, 'x',bl, 'x',bl, 'x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    [bl, bl, bl, bl, bl, bl, bl, bl, 'x','x',bl, bl, bl, bl, bl, bl],
    [bl, wh, wh, wh, wh, wh, wh, bl, bl, bl, bl, rd, rd, rd, rd, bl],
    [bl, wh, wh, bl, bl, bl, wh, bl, rd, rd, rd, rd, bl, bl, rd, bl],
    [bl, wh, bl, wh, bl, wh, bl, bl, bl, bl, bl, rd, bl, bl, rd, bl],
    [bl, wh, bl, bl, bl, bl, wh, bl, rd, rd, rd, rd, bl, bl, rd, bl],
    [bl, wh, bl, bl, bl, bl, wh, bl, bl, bl, bl, rd, rd, rd, rd, bl],
    [bl, wh, wh, wh, wh, wh, wh, bl, 'x','x',bl, bl, bl, bl, bl, bl],
    [bl, bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x','x','x','x','x'],
];
myImages[1][8][0]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x',bl, bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, wh, wh, wh, wh, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, wh, bl, bl, bl, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, bl, wh, bl, wh, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, bl, bl, bl, bl, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wh, wh, wh, wh, wh, wh, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
];
myImages[1][8][1]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x',bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, 'x','x'],
    ['x','x',bl, wh, wh, wh, wh, wh, wh, wh, wh, wh, wh, bl, 'x','x'],
    ['x','x',bl, wh, bl, bl, wh, bl, bl, bl, wh, bl, wh, bl, 'x','x'],
    ['x','x',bl, wh, bl, bl, bl, wh, bl, wh, bl, bl, wh, bl, 'x','x'],
    ['x','x',bl, wh, bl, bl, bl, bl, bl, bl, bl, bl, wh, bl, 'x','x'],
    ['x','x',bl, wh, wh, wh, wh, wh, wh, wh, wh, wh, wh, bl, 'x','x'],
    ['x','x',bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, 'x','x'],
];
myImages[2]=[];
myImages[2][69]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x',bl, 'x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, bu, bl, 'x','x','x','x'],
    ['x','x','x',bl, bl, bl, bl, bu, bu, bl, bl, bl, 'x','x'],
    ['x','x',bl, bu, bu, bl, bu, bu, bu, bu, bl, bu, bl, 'x'],
    ['x',bl, bu, bu, bu, bu, bu, bu, bu, bu, bu, bl, bu, bl ],
    ['x',bl, bu, bl, bu, bl, bu, bu, bu, bl, bu, bl, bu, bl ],
    ['x','x',bl, bl, bu, bu, g.f,bu, g.f,bu, bu, bl, bl, 'x'],
    ['x','x','x',bl, bu, bu, bu, bu, bu, bu, bu, bl, 'x','x'],
    ['x','x',bl, bu, bu, bu, bu, bu, bu, bl, bl, 'x','x','x'],
    ['x','x',bl, bu, bu, bu, bu, bu, bu, bu, bl, 'x','x','x'],
];
myImages[2][0]=[];
myImages[2][1]=[];
myImages[2][2]=[];
myImages[2][3]=[];
myImages[2][4]=[];
myImages[2][5]=[];
myImages[2][6]=[];
myImages[2][7]=[];
myImages[2][8]=[];
myImages[2][0][0]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x',bl, bl ],
    ['x','x','x','x','x','x',bl, bl, bl, 'x','x',bl, bl, bl, bu, bl ],
    ['x','x','x','x',bl, bl, bu, bu, bu, bl, bl, bu, bu, bu, bl, 'x'],
    ['x','x','x',bl, bu, bu, bl, bu, bu, bu, bu, bu, bu, bu, bu, bl ],
    ['x','x',bl, bu, bu, bu, bu, bl, bu, bu, bl, bu, bu, bu, bl, bl ],
    ['x','x',bl, bu, bu, bu, bu, bu, bu, bu, bu, wn, bu, wn, bu, bl ],
    ['x','x',bl, bu, bu, bu, bu, bu, bu, bu, bu, bu, bu, bu, bl, 'x'],
    ['x','x',bl, bu, bu, bl, bl, bu, bl, bu, bu, bl, bl, bu, bl, 'x'],
    ['x','x',bl, bu, bu, bl, bu, bu, bl, bu, bu, bl, bu, bu, bl, 'x'],
    ['x','x','x',bl, bl, 'x',bl, bl, 'x',bl, bl, 'x',bl, bl, 'x','x'],
];
myImages[2][0][1]=myImages[2][0][0];
myImages[2][0][2]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x',bl, bl ],
    ['x','x','x','x','x','x',bl, bl, bl, 'x','x',bl, bl, bl, bu, bl ],
    ['x','x','x','x',bl, bl, bu, bu, bu, bl, bl, bu, bu, bu, bl, 'x'],
    ['x','x','x',bl, bu, bu, bl, bu, bu, bu, bu, bu, bu, bu, bu, bl ],
    ['x','x',bl, bu, bu, bu, bu, bl, bu, bu, bl, bu, bu, bu, bl, bl ],
    ['x','x',bl, bu, bu, bu, bu, bu, bu, bu, bu, wn, bu, wn, bu, bl ],
    ['x','x',bl, bu, bu, bu, bu, bu, bu, bu, bu, bu, bu, bu, bl, 'x'],
    ['x','x',bl, bu, bu, bl, bl, bu, bl, bu, bu, bl, bl, bu, bl, 'x'],
    ['x','x',bl, bu, bu, bl, bu, bu, bl, bu, bu, bl, bu, bu, bl, 'x'],
    ['x','x',bl, bu, bu, bl, bu, bu, bl, bu, bu, bl, bu, bu, bl, 'x'],
    ['x','x','x',bl, bl, 'x',bl, bl, 'x',bl, bl, 'x',bl, bl, 'x','x'],
];
myImages[2][0][3]=myImages[2][0][2];
myImages[2][1][0]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x',bl, bl ],
    ['x','x','x','x','x','x',bl, bl, bl, 'x','x',bl, bl, bl, bu, bl ],
    ['x','x','x','x',bl, bl, bu, bu, bu, bl, bl, bu, bu, bu, bl, 'x'],
    ['x','x','x',bl, bu, bu, bl, bu, bu, bu, bu, bu, bu, bu, bu, bl ],
    ['x','x',bl, bu, bu, bu, bu, bl, bu, bu, bl, bu, bu, bu, bl, bl ],
    ['x','x',bl, bu, bu, bu, bu, bu, bu, bu, bu, wn, bu, wn, bu, bl ],
    ['x','x',bl, bu, bu, bu, bu, bu, bu, bu, bu, bu, bu, bu, bl, 'x'],
    ['x','x',bl, bu, bu, bl, bu, bu, bl, bu, bu, bl, bu, bu, bl, 'x'],
    ['x','x','x',bl, bu, bu, bl, bl, 'x',bl, bu, bu, bl, bl, 'x','x'],
    ['x','x','x','x',bl, bl, bl, 'x','x','x',bl, bl, bl, 'x','x','x'],
];
myImages[2][1][1]=myImages[2][0][0];
myImages[2][1][2]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x',bl, bl ],
    ['x','x','x','x','x','x',bl, bl, bl, 'x','x',bl, bl, bl, bu, bl ],
    ['x','x','x','x',bl, bl, bu, bu, bu, bl, bl, bu, bu, bu, bl, 'x'],
    ['x','x','x',bl, bu, bu, bl, bu, bu, bu, bu, bu, bu, bu, bu, bl ],
    ['x','x',bl, bu, bu, bu, bu, bl, bu, bu, bl, bu, bu, bu, bl, bl ],
    ['x','x',bl, bu, bu, bu, bu, bu, bu, bu, bu, wn, bu, wn, bu, bl ],
    ['x','x',bl, bu, bu, bu, bu, bu, bu, bu, bu, bu, bu, bu, bl, 'x'],
    ['x',bl, bu, bu, bu, bl, bu, bu, bl, bu, bu, bl, bu, bu, bl, 'x'],
    ['x',bl, bu, bu, bl, 'x',bl, bl, bu, bu, bl, 'x',bl, bu, bu, bl ],
    ['x',bl, bl, bl, 'x','x','x',bl, bl, bl, 'x','x','x',bl, bl, bl ],
];
myImages[2][1][3]=myImages[2][0][0];
myImages[2][2][0]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x',bl, bl ],
    ['x','x','x','x','x','x',bl, bl, bl, 'x','x',bl, bl, bl, bu, bl ],
    ['x','x','x','x',bl, bl, bu, bu, bu, bl, bl, bu, bu, bu, bl, 'x'],
    ['x','x','x',bl, bu, bu, bl, bu, bu, bu, bu, bu, bu, bu, bu, bl ],
    ['x','x',bl, bu, bu, bu, bu, bl, bu, bu, bl, bu, bu, bu, bl, bl ],
    ['x','x',bl, bu, bu, bu, bu, bu, bu, bu, bu, wn, bu, wn, bu, bl ],
    ['x','x',bl, bu, bu, bu, bu, bu, bu, bu, bu, bu, bu, bu, bl, 'x'],
    ['x','x',bl, bu, bu, bl, bl, bu, bl, bu, bu, bl, bl, bu, bl, 'x'],
    ['x','x','x',bl, bl, 'x',bl, bl, 'x',bl, bl, 'x',bl, bl, 'x','x'],
];
myImages[2][3][0]=myImages[2][1][2];
myImages[2][3][1]=myImages[2][1][2];
myImages[2][4][0]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x',bu ],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x',bl, bu, 'x'],
    ['x','x','x','x','x','x',bl, bl, bl, 'x','x',bl, bl, bl, bl, 'x'],
    ['x','x','x','x',bl, bl, bu, bu, bu, bl, bl, bu, bu, bu, bu, bl ],
    ['x','x','x',bl, bu, bu, bl, bu, bu, bu, bu, bu, bu, bu, bu, bl ],
    ['x','x',bl, bu, bu, bu, bu, bl, bu, bu, bl, bu, bu, bu, bl, bl ],
    ['x','x',bl, bu, bu, bu, bu, bu, bu, bu, bu, wn, bu, wn, bu, bl ],
    ['x','x',bl, bu, bu, bu, bu, bu, bu, bu, bu, bu, bu, bu, bl, 'x'],
    ['x',bl, bu, bu, bu, bl, bl, bu, bu, bl, bu, bl, bu, bu, bl, 'x'],
    ['x',bl, bu, bu, bl, bu, bu, bu, bl, bu, bu, bl, bu, bu, bl, 'x'],
    ['x','x',bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, bl, 'x','x'],
];
myImages[2][4][1]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x',bl ],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x',bl, bl, 'x'],
    ['x','x','x','x','x','x',bl, bl, bl, 'x','x',bl, bl, bl, bl, 'x'],
    ['x','x','x','x',bl, bl, bu, bu, bu, bl, bl, bu, bu, bu, bu, bl ],
    ['x','x','x',bl, bu, bu, bl, bu, bu, bu, bu, bu, bu, bu, bu, bl ],
    ['x','x',bl, bu, bu, bu, bu, bl, bu, bu, bl, bu, bu, bu, bl, bl ],
    ['x','x',bl, bu, bu, bu, bu, bu, bu, bu, bu, wn, bu, wn, bu, bl ],
    ['x','x',bl, bu, bu, bu, bu, bu, bu, bu, bu, bu, bu, bu, bl, 'x'],
    ['x',bl, bu, bu, bl, bl, bu, bl, bu, bu, bl, bl, bu, bl, 'x','x'],
    ['x',bl, bu, bu, bl, bu, bu, bl, bu, bu, bl, bu, bu, bl, 'x','x'],
    ['x','x',bl, bl, 'x',bl, bl, 'x',bl, bl, 'x',bl, bl, 'x','x','x'],
];
myImages[2][5][0]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x',bl, bl ],
    ['x','x','x','x','x','x',bl, bl, bl, bl, bl, bl, bl, bl, bu, bl ],
    ['x','x','x','x',bl, bl, bu, bu, bu, bu, bl, bu, bu, bu, bl, 'x'],
    ['x','x','x',bl, bu, bu, bl, bu, bu, wn, wn, bu, bu, bu, wn, wn ],
    ['x','x',bl, bu, bu, bu, bu, bl, bu, wn, bl, bu, bu, bu, wn, bl ],
    ['x','x',bl, bu, bu, bu, bu, bu, bu, bu, bu, wn, bu, wn, bu, bl ],
    ['x','x',bl, bu, bu, bu, bu, bu, bu, bu, bu, bu, bu, bu, bl, 'x'],
    ['x','x',bl, bu, bu, bl, bl, bu, bl, bu, bu, bl, bl, bu, bl, 'x'],
    ['x','x',bl, bu, bu, bl, bu, bu, bl, bu, bu, bl, bu, bu, bl, 'x'],
    ['x','x','x',bl, bl, 'x',bl, bl, 'x',bl, bl, 'x',bl, bl, 'x','x'],
];
myImages[2][6][0]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x',bl, bl ],
    ['x','x','x','x','x','x','x','x','x','x','x',bl, bl, bl, bu, bl ],
    ['x','x','x','x','x','x','x','x','x',bl, bl, bu, bu, bu, bl, 'x'],
    ['x','x','x','x','x','x',bl, bl, bl, bu, bu, bu, bu, bu, bu, bl ],
    ['x','x','x','x',bl, bl, bu, bu, bu, bu, bl, bu, bu, bu, bl, bl ],
    ['x','x','x',bl, bu, bu, bl, bu, bu, bu, bu, wn, bu, wn, bu, bl ],
    ['x','x',bl, bu, bu, bu, bu, bl, bu, bu, bu, bu, bu, bu, bu, bl ],
    ['x','x',bl, bu, bu, bu, bu, bu, bu, bu, bu, bu, bu, bu, bl, bl ],
    ['x','x',bl, bu, bu, bu, bu, bu, bl, bu, bu, bl, bu, bu, bl, 'x'],
    ['x','x',bl, bu, bu, bl, bl, bu, bl, bu, bu, bl, bl, bl, 'x','x'],
    ['x','x',bl, bu, bu, bl, bu, bu, bl, bl, bl, 'x','x','x','x','x'],
    ['x','x','x',bl, bl, 'x',bl, bl, 'x','x','x','x','x','x','x','x'],
];
myImages[2][6][1]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x',bl, bl ],
    ['x','x','x','x','x','x','x','x','x','x','x',bl, bl, bl, bu, bl ],
    ['x','x','x','x','x',bl, bl, bl, 'x',bl, bl, bu, bu, bu, bl, 'x'],
    ['x','x','x','x',bl, bu, bu, bu, bl, bu, bu, bu, bu, bu, bu, bl ],
    ['x','x','x',bl, bl, bl, bu, bu, bu, bu, bl, bu, bu, bu, bl, bl ],
    ['x','x','x',bl, bu, bu, bl, bl, bu, bu, bu, wn, bu, wn, bu, bl ],
    ['x','x',bl, bu, bu, bu, bu, bu, bu, bu, bu, bu, bu, bu, bu, bl ],
    ['x','x',bl, bu, bu, bu, bu, bu, bu, bu, bu, bu, bu, bu, bl, bl ],
    ['x','x',bl, bu, bu, bl, bl, bu, bl, bu, bu, bl, bu, bu, bl, 'x'],
    ['x','x',bl, bu, bu, bl, bu, bu, bl, bu, bu, bl, bl, bl, 'x','x'],
    ['x','x','x',bl, bl, 'x',bl, bl, 'x',bl, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
];
myImages[2][7][0]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x',rd, 'x','x','x',rd, 'x',bl, bl ],
    ['x','x','x','x','x',rd, bl, bl, bl, 'x',rd, bl, bl, bl, bu, bl ],
    ['x','x','x',rd, bl, bl, bu, bu, bu, bl, bl, bu, bu, bu, bl, 'x'],
    ['x','x','x',bl, bu, bu, bl, bu, bu, bu, bu, bu, bu, bu, bu, bl ],
    ['x','x',bl, bu, bu, bu, bu, bl, bu, bl, bl, bu, bu, bu, bl, bl ],
    ['x','x',bl, bu, bu, bu, bu, bu, bu, bu, bu, wn, bu, wn, bu, bl ],
    ['x','x',bl, bu, bu, bu, bu, bu, bu, bu, bu, bu, bu, bu, bl, 'x'],
    ['x','x',bl, bu, bu, bl, bl, bu, bl, bu, bu, bl, bl, bu, bl, 'x'],
    ['x','x',bl, bu, bu, bl, bu, bu, bl, bu, bu, bl, bu, bu, bl, 'x'],
    ['x','x','x',bl, bl, 'x',bl, bl, 'x',bl, bl, 'x',bl, bl, 'x','x'],
];
myImages[2][7][1]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x',rd, 'x','x','x',rd, 'x','x','x'],
    ['x','x','x','x','x',rd, 'x',rd, rd, 'x',rd, 'x',rd, 'x',bl, rd ],
    ['x','x','x',rd, 'x',rd, bl, bl, bl, 'x',rd, bl, bl, bl, bu, bl ],
    ['x','x','x',rd, bl, bl, bu, bu, bu, bl, bl, bu, bu, bu, bl, 'x'],
    ['x','x',rd, bl, bu, bu, bl, bu, bu, bl, bu, bu, bu, bu, bu, bl ],
    ['x','x',bl, bu, bu, bu, bu, bl, bu, bl, bl, bu, bu, bu, bl, bl ],
    ['x','x',bl, bu, bu, bu, bu, bu, bu, bu, bu, wn, bu, wn, bu, bl ],
    ['x','x',bl, bu, bu, bu, bu, bu, bu, bu, bu, bu, bu, bu, bl, 'x'],
    ['x','x',bl, bu, bu, bl, bl, bu, bl, bu, bu, bl, bl, bu, bl, 'x'],
    ['x','x',bl, bu, bu, bl, bu, bu, bl, bu, bu, bl, bu, bu, bl, 'x'],
    ['x','x','x',bl, bl, 'x',bl, bl, 'x',bl, bl, 'x',bl, bl, 'x','x'],
];
myImages[2][7][2]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x',rd, 'x','x','x',rd, 'x','x','x'],
    ['x','x','x','x','x',rd, 'x',rd, rd, 'x',rd, 'x',rd, 'x','x','x'],
    ['x','x','x',rd, 'x',rd, 'x',rd, rd, 'x',rd, rd, rd, 'x',rd, rd ],
    ['x','x','x',rd, rd, rd, bl, bl, bl, rd, rd, bl, bl, rd, bl, rd ],
    ['x','x',rd, rd, bl, bl, bu, bu, bu, bl, bl, bu, bu, bu, bl, 'x'],
    ['x','x',rd, bl, bu, bu, bl, bu, bu, rd, bu, bu, bu, bu, bu, bl ],
    ['x','x',bl, bu, bu, bu, bu, bl, bu, rd, rd, bu, bu, bu, rd, bl ],
    ['x','x',bl, bu, bu, bu, bu, bu, bu, bu, bu, wn, bu, wn, bu, bl ],
    ['x','x',bl, bu, bu, bu, bu, bu, bu, bu, bu, bu, bu, bu, bl, 'x'],
    ['x','x',bl, bu, bu, bl, bl, bu, bl, bu, bu, bl, bl, bu, bl, 'x'],
    ['x','x',bl, bu, bu, bl, bu, bu, bl, bu, bu, bl, bu, bu, bl, 'x'],
    ['x','x','x',bl, bl, 'x',bl, bl, 'x',bl, bl, 'x',bl, bl, 'x','x'],
];
myImages[2][8][0]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x',bl, bl, 'x'],
    ['x','x','x','x','x',bl, bl, bl, 'x','x',bl, bl, bl, bu, bl, 'x'],
    ['x','x','x',bl, bl, bu, bu, bu, bl, bl, bu, bu, bu, bl, 'x','x'],
    ['x','x',bl, bu, bu, bl, bu, bu, bu, bu, bu, bu, bu, bu, bl, 'x'],
    ['x',bl, bu, bu, bu, bu, bl, bu, bu, bl, bu, bu, bu, bl, bl, 'x'],
    ['x',bl, bu, bu, bu, bu, bu, bu, bu, bu, wn, bu, wn, bu, bl, 'x'],
    ['x',bl, bu, bu, bu, bu, bu, bu, bu, bu, bu, bu, bu, bl, 'x','x'],
    ['x',bl, bu, bu, bl, bl, bu, bl, bu, bu, bl, bl, bu, bu, bl, 'x'],
    ['x',bl, bu, bu, bl, bu, bu, bl, bl, bu, bu, bl, bu, bu, bl, 'x'],
    ['x','x',bl, bl, 'x',bl, bl, 'x','x',bl, bl, 'x',bl, bl, 'x','x'],
];
myImages[2][8][1]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x',bl, bl ],
    ['x','x','x','x','x','x',bl, bl, bl, 'x','x',bl, bl, bl, bu, bl ],
    ['x','x','x','x',bl, bl, bu, bu, bu, bl, bl, bu, bu, bu, bl, 'x'],
    ['x','x','x',bl, bu, bu, bl, bu, bu, bu, bu, bu, bu, bu, bu, bl ],
    ['x','x',bl, bu, bu, bu, bu, bl, bu, bu, bl, bu, bu, bu, bl, bl ],
    ['x','x',bl, bu, bu, bu, bu, bu, bu, bu, bu, wn, bu, wn, bu, bl ],
    ['x','x',bl, bu, bu, bu, bu, bu, bu, bu, bu, bu, bu, bu, bl, 'x'],
    ['x',bl, bu, bu, bu, bl, bl, bu, bl, bu, bu, bl, bl, bu, bl, 'x'],
    ['x',bl, bu, bu, bu, bl, bu, bu, bl, bu, bu, bl, bu, bu, bl, 'x'],
    ['x','x',bl, bl, 'x',bl, bl, bl, 'x',bl, bl, 'x',bl, bl, 'x','x'],
];
myImages[3]=[];
myImages[3][69]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x',bl, bl, bl, bl, bl, bl, bl, 'x','x','x'],
    ['x','x','x','x',bl, wh, wh, wh, bl, g.a,bl, 'x','x','x'],
    ['x','x','x','x',bl, wh, wh, wh, bl, g.b,bl, 'x','x','x'],
    ['x','x','x','x',bl, wh, wh, wh, bl, g.c,bl, 'x','x','x'],
    ['x','x','x','x',bl, wh, wh, wh, bl, g.d,bl, 'x','x','x'],
    ['x','x','x','x',bl, wh, wh, wh, bl, g.e,bl, 'x','x','x'],
    ['x','x','x','x',bl, wh, wh, wh, bl, g.f,bl, 'x','x','x'],
    ['x','x','x','x',bl, bl, bl, bl, bl, bl, bl, 'x','x','x'],
];
myImages[3][0]=[];
myImages[3][1]=[];
myImages[3][2]=[];
myImages[3][3]=[];
myImages[3][4]=[];
myImages[3][5]=[];
myImages[3][6]=[];
myImages[3][7]=[];
myImages[3][8]=[];
myImages[3][9]=[];
myImages[3][0][0]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x',bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, bl, g.a,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, bl, g.b,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, bl, g.c,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, bl, g.d,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, bl, g.e,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, bl, g.f,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
];
myImages[3][0][1]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x',bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, bl, g.b,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, bl, g.c,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, bl, g.d,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, bl, g.e,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, bl, g.f,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, bl, g.f,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
];
myImages[3][0][2]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x',bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, bl, g.b,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, bl, g.b,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, bl, g.c,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, bl, g.e,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, bl, g.f,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, bl, g.f,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
];
myImages[3][0][3]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x',bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, bl, g.b,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, bl, g.b,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, bl, g.c,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, bl, g.d,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, bl, g.e,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, bl, g.f,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
];
myImages[3][1][0]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, bl, bl, bl, bl, bl, bl, 'x','x','x'],
    ['x','x','x','x','x','x',bl, wh, wh, wh, bl, g.a,bl, 'x','x','x'],
    ['x','x','x','x','x','x',bl, wh, wh, wh, bl, g.b,bl, 'x','x','x'],
    ['x','x','x','x','x',bl, bl, wh, wh, wh, bl, g.c,bl, 'x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, wh, bl, g.d,bl, 'x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, bl, g.e,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, bl, g.f,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
];
myImages[3][1][1]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, bl, bl, bl, bl, bl, bl, 'x','x','x'],
    ['x','x','x','x','x','x',bl, wh, wh, wh, bl, g.a,bl, 'x','x','x'],
    ['x','x','x','x','x',bl, bl, wh, wh, wh, bl, g.b,bl, 'x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, wh, bl, g.c,bl, 'x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, wh, bl, g.d,bl, 'x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, bl, g.e,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, bl, g.f,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
];
myImages[3][1][3]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, bl, bl, bl, bl, bl, bl, 'x','x','x'],
    ['x','x','x','x','x','x',bl, wh, wh, wh, bl, g.a,bl, 'x','x','x'],
    ['x','x','x','x','x',bl, bl, wh, wh, wh, bl, g.b,bl, 'x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, wh, bl, g.c,bl, 'x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, bl, g.d,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, bl, g.e,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, bl, g.f,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
];
myImages[3][1][2]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, bl, bl, bl, bl, bl, bl, 'x','x','x'],
    ['x','x','x','x','x','x',bl, wh, wh, wh, bl, g.a,bl, 'x','x','x'],
    ['x','x','x','x','x','x',bl, wh, wh, wh, bl, g.b,bl, 'x','x','x'],
    ['x','x','x','x','x',bl, bl, wh, wh, wh, bl, g.c,bl, 'x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, bl, g.d,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, bl, g.e,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, bl, g.f,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
];
myImages[3][2][0]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x',bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, g.b,g.c,g.d,g.e,g.f,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
];
myImages[3][3][0]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x',bl, bl, bl, bl, bl, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, bl, g.a,bl, 'x','x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, bl, g.b,bl, 'x','x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, bl, g.c,bl, 'x','x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, bl, g.d,bl, 'x','x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, bl, g.e,bl, 'x','x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, bl, g.f,bl, 'x','x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, bl, g.f,bl, 'x','x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, bl, g.f,bl, 'x','x','x','x','x'],
    ['x','x','x','x','x',bl, bl, bl, bl, bl, bl, 'x','x','x','x','x'],
];
myImages[3][3][1]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x',bl, bl, bl, bl, bl, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, bl, g.a,bl, 'x','x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, bl, g.b,bl, 'x','x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, bl, g.c,bl, 'x','x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, bl, g.d,bl, 'x','x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, bl, g.e,bl, 'x','x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, bl, g.f,bl, 'x','x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, bl, g.f,bl, 'x','x','x','x','x'],
    ['x','x','x','x','x',bl, bl, bl, bl, bl, bl, 'x','x','x','x','x'],
];
myImages[3][4][0]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x',tbl, tbl, tbl, tbl, tbl, tbl, tbl, 'x','x','x','x'],
    ['x','x','x','x','x',tbl, twh, twh, twh, tbl, twh, tbl, 'x','x','x','x'],
    ['x','x','x','x','x',tbl, twh, twh, twh, tbl, twh, tbl, 'x','x','x','x'],
    ['x','x','x','x','x',tbl, twh, twh, twh, tbl, twh, tbl, 'x','x','x','x'],
    ['x','x','x','x','x',tbl, twh, twh, twh, tbl, twh, tbl, 'x','x','x','x'],
    ['x','x','x','x','x',tbl, twh, twh, twh, tbl, twh, tbl, 'x','x','x','x'],
    ['x','x','x','x','x',tbl, twh, twh, twh, tbl, twh, tbl, 'x','x','x','x'],
    ['x','x','x','x','x',tbl, tbl, tbl, tbl, tbl, tbl, tbl, 'x','x','x','x'],
];
myImages[3][4][1]=myImages[3][4][0];
myImages[3][5][0]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x',bl, bl, bl, 'x',bl, bl, bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, bl, bl, g.a,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, bl, g.b,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, bl, g.c,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, bl, g.d,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, bl, g.e,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, wh, bl, g.f,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
];
myImages[3][6][0]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, bl, 'x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, wh, wh, bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x',bl, wh, bl, bl, wh, bl, 'x','x','x','x','x'],
    ['x','x','x','x',bl, wh, bl, 'x','x',bl, wh, bl, 'x','x','x','x'],
    ['x','x','x',bl, wh, bl, 'x','x','x','x',bl, wh, bl, 'x','x','x'],
    ['x','x',bl, wh, bl, 'x','x','x','x','x','x',bl, wh, bl, 'x','x'],
    ['x','x','x',bl, 'x','x','x','x','x','x','x','x',bl, 'x','x','x'],
];
myImages[3][6][1]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x',bl, bl, 'x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, wh, wh, bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, wh, wh, bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, wh, wh, bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, wh, wh, bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, wh, wh, bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, wh, wh, bl, 'x','x','x','x','x','x'],
    ['x','x','x','x','x','x',bl, bl, bl, bl, 'x','x','x','x','x','x'],
];
myImages[3][7][0]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x',bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, bl, g.a,g.a,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, bl, g.b,g.b,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, bl, g.c,g.c,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, bl, g.d,g.d,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, bl, g.e,g.e,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, bl, g.f,g.f,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
];
myImages[3][7][1]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x',bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, bl, rd, g.a,g.a,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, bl, g.a,g.b,g.b,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, bl, g.b,g.c,g.c,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, bl, g.c,g.d,g.d,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, bl, g.d,g.e,g.e,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, bl, rd, g.f,g.f,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
];
myImages[3][7][2]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x',bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, bl, rd, g.a,g.a,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, bl, rd, g.b,g.b,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, bl, rd, g.c,g.c,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, bl, rd, g.d,g.d,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, bl, rd, g.e,g.e,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, bl, rd, g.f,g.f,bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
];
myImages[3][7][3]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x',bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, bl, rd, rd, rd, bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, bl, rd, rd, rd, bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, bl, rd, rd, rd, bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, bl, rd, rd, rd, bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, bl, rd, rd, rd, bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, bl, rd, rd, rd, bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
];
myImages[3][7][4]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x',rd, 'x','x','x','x','x'],
    ['x','x','x',rd, 'x','x','x',rd, 'x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x',bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, bl, rd, rd, rd, bl, 'x',rd, 'x','x'],
    ['x','x','x','x','x',bl, wh, bl, rd, rd, rd, bl, 'x','x','x','x'],
    ['x','x','x','x',rd, bl, wh, bl, rd, rd, rd, bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, bl, rd, rd, rd, bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, bl, rd, rd, rd, bl, rd, 'x','x','x'],
    ['x','x','x',rd, 'x',bl, wh, bl, rd, rd, rd, bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
];
myImages[3][7][5]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x',rd, 'x','x','x','x'],
    ['x','x','x',rd, 'x','x','x',rd, 'x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x',rd, 'x','x','x','x','x'],
    ['x','x','x','x',rd, bl, bl, bl, bl, bl, bl, bl, 'x','x',rd, 'x'],
    ['x','x','x','x','x',bl, wh, bl, rd, rd, rd, bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, bl, rd, rd, rd, bl, 'x','x','x','x'],
    ['x','x','x',rd, 'x',bl, wh, bl, rd, rd, rd, bl, rd, 'x','x','x'],
    ['x','x','x','x','x',bl, wh, bl, rd, rd, rd, bl, 'x','x','x','x'],
    ['x','x','x','x',rd, bl, wh, bl, rd, rd, rd, bl, 'x',rd, 'x','x'],
    ['x','x',rd, 'x','x',bl, wh, bl, rd, rd, rd, bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
];
myImages[3][7][6]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x',rd, 'x','x','x'],
    ['x','x','x',rd, 'x','x','x',rd, 'x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x',rd, 'x','x','x','x','x'],
    ['x','x','x','x',rd, 'x','x','x',rd, 'x','x','x','x','x','x',rd ],
    ['x','x','x','x','x',bl, bl, bl, bl, rd, bl, bl, rd, 'x','x','x'],
    ['x','x','x','x','x',bl, wh, bl, rd, rd, rd, bl, 'x','x','x','x'],
    ['x','x',rd, 'x','x',bl, wh, bl, rd, rd, rd, bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, rd, rd, rd, rd, rd, 'x',rd, 'x','x'],
    ['x','x','x','x',rd, bl, wh, rd, rd, rd, rd, rd, rd, 'x','x','x'],
    ['x','x','x','x','x',bl, wh, bl, rd, rd, rd, bl, 'x','x','x','x'],
    ['x','x','x',rd, 'x',bl, wh, bl, rd, rd, rd, bl, 'x','x',rd, 'x'],
    ['x',rd, 'x','x','x',bl, bl, bl, bl, rd, bl, bl, 'x','x','x','x'],
];
myImages[3][7][7]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x',bl, 'x','x','x'],
    ['x','x','x',bl, 'x','x','x',bl, 'x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x',bl, 'x','x','x','x','x'],
    ['x','x','x','x',bl, 'x','x','x',bl, 'x','x','x','x','x','x',rd ],
    ['x','x','x','x','x',bl, bl, bl, bl, bl, bl, bl, bl, 'x','x','x'],
    ['x','x','x','x','x',bl, wh, bl, bl, bl, bl, bl, 'x','x','x','x'],
    ['x','x',bl, 'x','x',bl, wh, bl, bl, bl, bl, bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, wh, bl, bl, bl, bl, bl, 'x',bl, 'x','x'],
    ['x','x','x','x',bl, bl, wh, bl, bl, bl, bl, bl, bl, 'x','x','x'],
    ['x','x','x','x','x',bl, wh, bl, bl, bl, bl, bl, 'x','x','x','x'],
    ['x','x','x',bl, 'x',bl, wh, bl, bl, bl, bl, bl, 'x','x',bl, 'x'],
    ['x',bl, 'x','x','x',bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
];
myImages[3][7][8]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x',rd, rd, rd, rd, rd, rd, rd, 'x','x','x','x'],
    ['x','x','x','x','x',rd, wh, rd, rd, rd, rd, rd, 'x','x','x','x'],
    ['x','x','x','x','x',rd, wh, rd, rd, rd, rd, rd, 'x','x','x','x'],
    ['x','x','x','x','x',rd, wh, rd, rd, rd, rd, rd, 'x','x','x','x'],
    ['x','x','x','x','x',rd, wh, rd, rd, rd, rd, rd, 'x','x','x','x'],
    ['x','x','x','x','x',rd, wh, rd, rd, rd, rd, rd, 'x','x','x','x'],
    ['x','x','x','x','x',rd, wh, rd, rd, rd, rd, rd, 'x','x','x','x'],
    ['x','x','x','x','x',rd, rd, rd, rd, rd, rd, rd, 'x','x','x','x'],
];
myImages[3][8][0]=myImages[3][2][0];
myImages[3][8][1]=myImages[3][2][0];
//myImages[3][9][0]=myImages[3][2][0];
//myImages[3][9][1]=myImages[3][2][0];
myImages[3][9][0]=myImages[3][0][0]; // frame1=9 and frame2=0 is a placeholder image, it doesn't need to be fleshed out.
myImages[3][9][1]=myImages[3][0][0];
myImages[3][9][2]=[
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'],
    ['x','x','x','x','x',bl, bl, bl, bl, bl, bl, 'x','x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, bl, g.a,bl, 'x','x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, bl, g.b,bl, 'x','x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, bl, g.c,bl, 'x','x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, bl, g.d,bl, 'x','x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, bl, g.e,bl, 'x','x','x','x','x'],
    ['x','x','x','x','x',bl, wh, wh, bl, g.f,bl, 'x','x','x','x','x'],
    ['x','x','x','x',bl, bl, bl, bl, bl, bl, bl, bl, 'x','x','x','x'],
    ['x','x','x','x',bl, wn, bl, wn, wn, bl, wn, bl, 'x','x','x','x'],
    ['x','x','x','x','x',bl, 'x',bl, bl, 'x',bl, 'x','x','x','x','x'],
];
myImages[3][9][3]=myImages[3][9][2];
    
// }
    if (myImages!==undefined) {
        return myImages;
    } else {
        return 1;
    }
};
globall.myImages = (globall.myImagees());
}
};

  // Get the canvas that ProcessingJS will use
  var canvas2 = document.getElementById("mycanvas"); 
  // Pass the function to ProcessingJS constructor
  var processingInstance2 = new Processing(canvas2, programCode2); 